### PR TITLE
Add google api stub for geocoder

### PR DESCRIPTION
**Pull request by nstjean**
This solves the errors when it tried to bump LBL to 1.6.0 in #92

### CODE REVIEW

**Comment by nstjean** [comment]
In LBL 1.6.0 the API got changed (by me) to the client-side version rather than the server-side version. There were no issues with the pages running, but it's causing a mess with the tests!

**Comment by nstjean** [comment]
This may not be necessary anymore, see my comments on https://github.com/publiclab/leaflet-blurred-location/pull/235#issuecomment-576817901

**Comment by jywarren** [comment]
Should we merge it anyways? Or hold off?

**Comment by nstjean** [comment]
I'd like to hold off and merge in the bumped LBL with change and see what happens.

**Comment by nstjean** [comment]
This is solved in https://github.com/publiclab/leaflet-blurred-location-display/pull/95

**Pull request closed without merging**
