### PR TITLE
Markers color changed according to precision .

### LINKED ISSUE #44: color code the markers and coordinate text so that people can distinguish the different precisions visually
> Can we also open a new issue to color code the markers and coordinate text so that people can distinguish the different precisions visually?
> 
> And one to default to geoJson for Json parsing?

- [x] Give different colors to markers according to their precision .

(kindly elaborate these 😄 !) 
- [x]  coordinate text 

- [ ] one to default to geoJson for Json parsing

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Fixes #44 😄 !

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
**/index.html**
screenshot 2019-02-22 at 1 15 14 pm

**/example.html**
screenshot 2019-02-22 at 1 15 05 pm

**Comment by sagarpreet-chadha** [comment]
screenshot 2019-02-22 at 1 28 09 pm

**Comment by jywarren** [comment]
This is awesome!!! Thanks, @sagarpreet-chadha !!!

**Comment by jywarren** [comment]
Could you merge to gh-pages and publish so we can demo this? Thanks!!!

**Comment by sagarpreet-chadha** [comment]
Demo live @ https://publiclab.github.io/leaflet-blurred-location-display/examples/example.html 😄 !

**Pull request merged**
