### PR TITLE
Only add popup if rect contains markers

### PR DESCRIPTION
**Pull request by jywarren**
We may need to check if we need a popup to exist upon modifying the markers on the map with subsequent data loads; should we instead make an empty popup? Or, does it later detect that no popup exists and creates one, or does it flush all popups and regenerate them on new data being loaded?

### CODE REVIEW

**Comment by jywarren** [comment]
Also I'm not seeing the people getting displayed. We should write a test for this:

image

(took some zooming in and out at https://stable.publiclab.org/map#9/41.75603585779898/-71.4263141155243)

Screen Shot 2021-02-23 at 3 26 38 PM

**Comment by daemon1024** [comment]
What's the blocker here?

**Comment by daemon1024** [comment]
https://user-images.githubusercontent.com/47106543/128615069-1ec77818-35a1-4dac-8316-27f8da4a31c1.mp4

I tried it out after a popup fix https://github.com/daemon1024/leaflet-blurred-location-display/commit/6564091799a0b05a7877ded20a63433c0fd748f2 seemed to work fine.

**Comment by jywarren** [comment]
I think this is good, we may just be waiting for the GitHub Actions work by @aliciapaz in https://github.com/publiclab/plots2/issues/9641 to get to this repository before merging. 

I do notice that in the fix you cite, it's showing that there are "2 people" but we should be instead showing a list of the people, like:

```
* firstPerson
* secondPerson
```

**Comment by jywarren** [comment]
Aha, ok your fix looks great! So we can probably merge this already, esp since you've manually tested. Then let's address the list of users next in a separate issue/PR.

**Comment by jywarren** [comment]
OK, i brought it in with a PR. Now merging this. Thank you!!!

**Comment by jywarren** [comment]
Published as v1.3.1! https://www.npmjs.com/package/leaflet.blurred-location-display

**Comment by jywarren** [comment]
OK this should now show up on plots2 -- let's link when it does.

**Comment by jywarren** [comment]
https://github.com/publiclab/leaflet-environmental-layers/pull/536

**Pull request merged**
