### PR TITLE
Add/remove markers as zoom level change .

### LINKED ISSUE #18: Add/remove markers as zoom level change .
Reference : https://github.com/publiclab/leaflet-blurred-location-display/issues/9#issuecomment-383973448

> So does this make sense? That in this library, as you zoom in, some locations appear only within some zoom levels, that are close to the precision they were entered in? If they have lots of precision, they might appear in many zoom levels, but if they are very imprecise (highly blurred), they would be hidden once you zoom in too far.

> We could write a test to check for this -- so it would start the map up, go to a certain zoom level, and check what's visible, then zoom in further and check again, for 3 or 4 zoom levels. Then we could write the functions of this library to ensure that the markers are properly displayed for those given zoom levels.

### PR DESCRIPTION
**Pull request by sagarpreet-chadha**
Fixes #18 !
Work in Progress . 

Hi @icarito ...can you kindly remove the CORS from /api routes ?  Thanks !
Currently using `https://publiclab.org/api/srch/nearbyPeople` .

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
lbld_gif_1


@jywarren ...kindly see this 😄 ! I will add spinners next .

**Comment by jywarren** [comment]
This is super. Great work! Tell me when it's ready to merge; we can use the `ready` label maybe. 

We'll probably want to add more interface soon to help illustrate what's going on here. But can be in a follow-up PR. What do you think -- maybe, could we somehow display the precision of each point in the marker popover, so you can sort of "check" that it's working properly?

**Comment by jywarren** [comment]
I'd like to change the default branch to `main` as we slowly do this for all PL repos... just a heads up and maybe we could open this against that instead? thanks!!!

**Comment by sagarpreet-chadha** [comment]
Shifted to #22 !

**Pull request closed without merging**
